import type { HomeLocale } from '@/lib/locale';

import type { HomeContent } from './types';

export const content: HomeContent = {
  en: {
    eyebrow: 'Spec-driven development for AI-assisted teams',
    title: 'Build with agents, but keep humans in charge.',
    description:
      'AI SDLC Kit organizes planning, implementation, QA, and review into a disciplined workflow with explicit checkpoints, reusable artifacts, and multilingual documentation.',
    primaryCta: 'Open the docs',
    secondaryCta: 'See the agents',
    languageLabel: 'Read in',
    highlights: [
      { value: '10', label: 'specialized agents' },
      { value: '2', label: 'delivery flows' },
      { value: '3', label: 'supported languages' },
    ],
    panels: [
      {
        title: 'Discovery to operations',
        text: 'Start from a raw idea or a scoped task and move through PRD, technical spec, implementation, QA, and review without losing the thread.',
        href: '/en/get-started/how-it-works',
        linkLabel: 'How it works',
      },
      {
        title: 'Human-in-the-loop by design',
        text: 'The kit treats approval gates as part of the system, not as optional ceremony, so risky assumptions are caught before code lands.',
        href: '/en/guide/HITL-checkpoints',
        linkLabel: 'HITL checkpoints',
      },
      {
        title: 'Reference-ready artifacts',
        text: 'Use the built-in prompts, templates, and artifact contracts to keep outputs consistent across planning and implementation.',
        href: '/en/reference/templates',
        linkLabel: 'Browse templates',
      },
    ],
    workflowTitle: 'From idea to production,\nwithout losing the thread.',
    steps: [
      { num: '01', phase: 'Discovery', desc: 'A raw idea becomes a structured, unbiased product spec.' },
      { num: '02', phase: 'PM Spec', desc: 'User journeys, personas, and business rules are formalized.' },
      { num: '03', phase: 'Tech PRD', desc: 'Requirements gain measurable acceptance criteria and scope boundaries.' },
      { num: '04', phase: 'Architecture', desc: 'Technical spec, ordered epics, and per-epic artefacts are generated.' },
      { num: '05', phase: 'Build & Review', desc: 'Implementer writes code. QA validates. Reviewer approves.' },
      { num: '06', phase: 'Ops & Release', desc: 'Observability, anomaly patterns, and deploy pipeline are closed.' },
    ],
    agentsTitle: 'Ten agents. One coherent pipeline.',
    agentCards: [
      {
        tag: '🧭',
        name: 'Discovery',
        desc: 'Structures raw ideas without technical bias. The first agent in Flow A.',
        flow: 'Flow A',
        href: '/en/reference/agents',
        featured: true,
      },
      {
        tag: '🗂️',
        name: 'PM',
        desc: 'Translates the structured idea into a functional spec with user journeys.',
        flow: 'Flow A',
        href: '/en/reference/agents',
      },
      {
        tag: '🧑‍💼',
        name: 'Tech Lead',
        desc: 'Bridges product and engineering — turns the functional spec into a full PRD.',
        flow: 'Flow A',
        href: '/en/reference/agents',
      },
      {
        tag: '🏗️',
        name: 'Architect',
        desc: 'Produces the full technical architecture, epics breakdown, and per-epic artefacts.',
        flow: 'Flow A',
        href: '/en/reference/agents',
      },
      {
        tag: '📥',
        name: 'Intake',
        desc: 'Structures a raw task description into a scoped, unambiguous deliverable.',
        flow: 'Flow B',
        href: '/en/reference/agents',
      },
      {
        tag: '📐',
        name: 'Planner',
        desc: 'Generates PRD and spec for Flow B tasks from the structured intake.',
        flow: 'Flow B',
        href: '/en/reference/agents',
      },
    ],
    ctaTitle: 'Start building with agents today.',
    ctaBody: 'The kit — agents, prompts, templates, and checkpoints — is open and ready to use.',
    ctaCta: 'Open the docs',
    footer: {
      tagline: 'Spec-driven AI workflows for engineering teams.',
      colGetStarted: 'Get Started',
      colGuide: 'Guide',
      colReference: 'Reference',
      copyright: '© 2026 AI SDLC Kit · MIT License',
    },
  },
  pt: {
    eyebrow: 'Spec-Driven Development para times com IA',
    title: 'Use agentes para acelerar, sem abrir mão do controle humano.',
    description:
      'O AI SDLC Kit organiza planejamento, implementação, QA e revisão em um fluxo disciplinado com checkpoints explícitos, artefatos reutilizáveis e documentação multilíngue.',
    primaryCta: 'Abrir a documentação',
    secondaryCta: 'Ver os agentes',
    languageLabel: 'Ler em',
    highlights: [
      { value: '10', label: 'agentes especializados' },
      { value: '2', label: 'fluxos de entrega' },
      { value: '3', label: 'idiomas suportados' },
    ],
    panels: [
      {
        title: 'Do discovery à operação',
        text: 'Comece por uma ideia bruta ou uma tarefa delimitada e avance por PRD, spec técnica, implementação, QA e review sem perder o contexto.',
        href: '/pt/get-started/how-it-works',
        linkLabel: 'Como funciona',
      },
      {
        title: 'Human-in-the-loop como regra',
        text: 'O kit trata aprovações como parte do sistema, não como burocracia opcional, para bloquear suposições frágeis antes que virem código.',
        href: '/pt/guide/HITL-checkpoints',
        linkLabel: 'Checkpoints HITL',
      },
      {
        title: 'Artefatos prontos para uso',
        text: 'Prompts, templates e contratos de artefatos ajudam a manter consistência entre planejamento, execução e revisão.',
        href: '/pt/reference/templates',
        linkLabel: 'Explorar templates',
      },
    ],
    workflowTitle: 'Da ideia à produção,\nsem perder o fio da meada.',
    steps: [
      { num: '01', phase: 'Discovery', desc: 'Uma ideia bruta vira uma spec de produto estruturada e sem viés técnico.' },
      { num: '02', phase: 'Spec de PM', desc: 'Jornadas de usuário, personas e regras de negócio são formalizadas.' },
      { num: '03', phase: 'Tech PRD', desc: 'Os requisitos ganham critérios de aceite mensuráveis e escopo delimitado.' },
      { num: '04', phase: 'Arquitetura', desc: 'Spec técnica, épicos ordenados e artefatos por épico são gerados.' },
      { num: '05', phase: 'Build & Review', desc: 'Implementer escreve o código. QA valida. Reviewer aprova.' },
      { num: '06', phase: 'Ops & Release', desc: 'Observabilidade, padrões de anomalia e pipeline de deploy são encerrados.' },
    ],
    agentsTitle: 'Dez agentes. Um pipeline coerente.',
    agentCards: [
      {
        tag: '🧭',
        name: 'Discovery',
        desc: 'Estrutura ideias brutas sem viés técnico. Primeiro agente do Flow A.',
        flow: 'Flow A',
        href: '/pt/reference/agents',
        featured: true,
      },
      {
        tag: '🗂️',
        name: 'PM',
        desc: 'Traduz a ideia estruturada em uma spec funcional com jornadas de usuário.',
        flow: 'Flow A',
        href: '/pt/reference/agents',
      },
      {
        tag: '🧑‍💼',
        name: 'Tech Lead',
        desc: 'Conecta produto e engenharia — transforma a spec funcional em um PRD completo.',
        flow: 'Flow A',
        href: '/pt/reference/agents',
      },
      {
        tag: '🏗️',
        name: 'Architect',
        desc: 'Produz arquitetura técnica completa, épicos ordenados e artefatos por épico.',
        flow: 'Flow A',
        href: '/pt/reference/agents',
      },
      {
        tag: '📥',
        name: 'Intake',
        desc: 'Estrutura uma tarefa bruta em um entregável delimitado e sem ambiguidades.',
        flow: 'Flow B',
        href: '/pt/reference/agents',
      },
      {
        tag: '📐',
        name: 'Planner',
        desc: 'Gera PRD e spec para tarefas do Flow B a partir do intake estruturado.',
        flow: 'Flow B',
        href: '/pt/reference/agents',
      },
    ],
    ctaTitle: 'Comece a criar com agentes hoje.',
    ctaBody: 'O kit — agentes, prompts, templates e checkpoints — está aberto e pronto para uso.',
    ctaCta: 'Abrir a documentação',
    footer: {
      tagline: 'Fluxos de IA guiados por especificação para times de engenharia.',
      colGetStarted: 'Início',
      colGuide: 'Guia',
      colReference: 'Referência',
      copyright: '© 2026 AI SDLC Kit · Licença MIT',
    },
  },
  es: {
    eyebrow: 'Spec-Driven Development para equipos con IA',
    title: 'Trabaja con agentes sin perder la decisión humana.',
    description:
      'AI SDLC Kit organiza planificación, implementación, QA y revisión en un flujo disciplinado con checkpoints explícitos, artefactos reutilizables y documentación multilingüe.',
    primaryCta: 'Abrir la documentación',
    secondaryCta: 'Ver agentes',
    languageLabel: 'Leer en',
    highlights: [
      { value: '10', label: 'agentes especializados' },
      { value: '2', label: 'flujos de entrega' },
      { value: '3', label: 'idiomas soportados' },
    ],
    panels: [
      {
        title: 'De discovery a operaciones',
        text: 'Empieza con una idea en bruto o una tarea acotada y avanza por PRD, spec técnica, implementación, QA y revisión sin perder el hilo.',
        href: '/es/get-started/how-it-works',
        linkLabel: 'Cómo funciona',
      },
      {
        title: 'Human-in-the-loop por diseño',
        text: 'El kit trata los puntos de aprobación como parte del sistema, no como ceremonia opcional, para detener supuestos débiles antes del código.',
        href: '/es/guide/HITL-checkpoints',
        linkLabel: 'Checkpoints HITL',
      },
      {
        title: 'Artefactos listos para referencia',
        text: 'Prompts, plantillas y contratos de artefactos mantienen coherencia entre planificación, implementación y revisión.',
        href: '/es/reference/templates',
        linkLabel: 'Ver plantillas',
      },
    ],
    workflowTitle: 'De la idea a producción,\nsin perder el hilo.',
    steps: [
      { num: '01', phase: 'Discovery', desc: 'Una idea en bruto se convierte en una spec de producto estructurada sin sesgo técnico.' },
      { num: '02', phase: 'Spec de PM', desc: 'Los journeys de usuario, personas y reglas de negocio se formalizan.' },
      { num: '03', phase: 'Tech PRD', desc: 'Los requisitos obtienen criterios de aceptación medibles y límites de alcance.' },
      { num: '04', phase: 'Arquitectura', desc: 'Se generan spec técnica, épicas ordenadas y artefactos por épica.' },
      { num: '05', phase: 'Build & Review', desc: 'El Implementer escribe código. QA valida. El Reviewer aprueba.' },
      { num: '06', phase: 'Ops & Release', desc: 'Observabilidad, patrones de anomalía y pipeline de deploy se cierran.' },
    ],
    agentsTitle: 'Diez agentes. Un pipeline coherente.',
    agentCards: [
      {
        tag: '🧭',
        name: 'Discovery',
        desc: 'Estructura ideas en bruto sin sesgo técnico. Primer agente de Flow A.',
        flow: 'Flow A',
        href: '/es/reference/agents',
        featured: true,
      },
      {
        tag: '🗂️',
        name: 'PM',
        desc: 'Traduce la idea estructurada en una spec funcional con journeys de usuario.',
        flow: 'Flow A',
        href: '/es/reference/agents',
      },
      {
        tag: '🧑‍💼',
        name: 'Tech Lead',
        desc: 'Conecta producto e ingeniería — convierte la spec funcional en un PRD completo.',
        flow: 'Flow A',
        href: '/es/reference/agents',
      },
      {
        tag: '🏗️',
        name: 'Architect',
        desc: 'Produce arquitectura técnica completa, épicas ordenadas y artefactos por épica.',
        flow: 'Flow A',
        href: '/es/reference/agents',
      },
      {
        tag: '📥',
        name: 'Intake',
        desc: 'Estructura una tarea en bruto en un entregable delimitado y sin ambigüedades.',
        flow: 'Flow B',
        href: '/es/reference/agents',
      },
      {
        tag: '📐',
        name: 'Planner',
        desc: 'Genera PRD y spec para tareas de Flow B a partir del intake estructurado.',
        flow: 'Flow B',
        href: '/es/reference/agents',
      },
    ],
    ctaTitle: 'Empieza a construir con agentes hoy.',
    ctaBody: 'El kit — agentes, prompts, plantillas y checkpoints — está abierto y listo para usar.',
    ctaCta: 'Abrir la documentación',
    footer: {
      tagline: 'Flujos de IA guiados por especificación para equipos de ingeniería.',
      colGetStarted: 'Inicio',
      colGuide: 'Guía',
      colReference: 'Referencia',
      copyright: '© 2026 AI SDLC Kit · Licencia MIT',
    },
  },
};

export const localeLabels: Record<HomeLocale, string> = {
  en: 'EN — English',
  pt: 'PT — Português',
  es: 'ES — Español',
};
